### ISSUE TITLE
BUG - Absolution's ion clouds sometimes instantly die

### ISSUE THREAD

**Issue by flexxyfluxx** [Cyrus106/Forgemaster-Project#9]
hello,

sorry if I'm being pushy by opening an Issue. I see that it says this repo is "for dev eyes only", but I couldn't figure out where else to make a bug known. so here I am.

This bug is in regards to the Absolution weapon.

Against some enemy ships, the ion clouds that are meant to spawn on hit wll instantly die. This seems wrong, seeing as  it doesn't happen against all enemies, and it makes the weapon randomly a lot weaker.

I have yet to recognize a pattern; I will add to this if/when I do.

**Comment by Kommandant-Julk** [comment]
with the introduction of that one tag that removes the warning when jumping away with certain crew, this should be resolved
